# Use an official Nginx image as a base
FROM nginx:stable

# Install necessary packages
RUN apt-get update && apt-get install -y \
    libmodsecurity3 \
    libmodsecurity-dev \
    libpcre3 libpcre3-dev \
    automake \
    autoconf \
    libtool \
    libssl-dev \
    git \
    build-essential \
    cmake

# Clone ModSecurity repository
RUN git clone --depth 1 -b v3/master --single-branch https://github.com/SpiderLabs/ModSecurity

# Build and install ModSecurity
WORKDIR /ModSecurity
RUN git submodule init && git submodule update
RUN ./build.sh
RUN ./configure
RUN make
RUN make install

# Copy the ModSecurity configuration file
RUN cp modsecurity.conf-recommended /etc/nginx/modsecurity.conf

# Fetch ModSecurity-nginx connector
WORKDIR /

RUN git clone --depth 1 https://github.com/SpiderLabs/ModSecurity-nginx.git

# Copy the OWASP ModSecurity Core Rule Set (CRS)
RUN git clone --depth 1 -b v3.3/master --single-branch https://github.com/coreruleset/coreruleset /etc/nginx/crs

# Configure Nginx to use ModSecurity
RUN sed -i '/http {/a modsecurity on;\nmodsecurity_rules_file /etc/nginx/crs/owasp-crs.conf;' /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
